### ISSUE TITLE
Exposing namenode to external application

### ISSUE THREAD

**Issue by siganapathy** [Comcast/kube-yarn#4]
I deployed your setup on our existing kubernetes cluster. As of now, i am only able to access zeppelin UI externally. i want my external client application to push data to hdfs. But looks like it is a headless service and not exposed outside the cluster. If i try to change the type of service to NodePort or LoadBalancer, then the jobs fail. What changes can i make inorder to expose the namenode to external applications?

**Comment by premkumar-masilamani** [comment]
Hi @siganapathy - The headless service present in the yarn-nm-statefulset.yaml is to enable unique network identifier for name node, so that the data nodes can discover the name node. Don't touch that. Instead create a new service with the type LoadBalancer.

```
---
apiVersion: v1
kind: Service
metadata:
  name: hdfs-name-node-service-external
spec:
  ports:
    - name: http
      port: 50070
      targetPort: 50070
  selector:
    component: hdfs-nn
  type: LoadBalancer
```
